<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>01eaffa0-e369-4e13-a908-5cbf5d264c57</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdocsTestTask.Core\EdocsTestTask.Core.csproj" />
    <ProjectReference Include="..\EdocsTestTask.Infrastructure\EdocsTestTask.Infrastructure.csproj" />
  </ItemGroup>

</Project>
